### ISSUE TITLE
Encrypt/Decrypt all notes

### ISSUE THREAD

**Issue by reversed-heartbeat** [tejado/obsidian-gpgCrypt#1]
Can you add a new feature where you can encrypt/decrypt all notes(markdown) in a single execution instead of manually encrypting/decrypting each notes? Thanks in advance. I like this plugin. Hopefully this works in mobile too.

**Comment by tejado** [comment]
@reversed-heartbeat 
Thanks for your feedback. This is a great idea. Would it be okay to encrypt it during the next write or should all notes encrypted during activation?

Out of curiosity: do you use OpenPGP.js or the gpg CLI wrapper?

**Comment by reversed-heartbeat** [comment]
That's a good one too! I think that would be really useful.
I use the latter since I'm a bit familiar with it. And thanks you for your dedication :) Looking forward~

**Comment by tejado** [comment]
Implemented in release https://github.com/tejado/obsidian-gpgCrypt/releases/tag/0.2.0
I would be delighted if you could give me some feedback on this.

**Comment by reversed-heartbeat** [comment]
Hey bro, I'm really sorry for the late reply. I've been really swamped with work lately, and I completely forgot about this until I saw your notification, but I just wanted to say that the improvement updates you made to your plugin are absolutely amazing! I've been using your plugin for a while now, and I'm always impressed with how you continue to improve it. <3

You've made the plugin even better than it was before and definitely a valuable asset to the community.  Thanks for all your hard work!

Keep up the good work bro! :)
