### ISSUE TITLE
Can't read a GPG file encrypted from outside Obsidian

### ISSUE THREAD

**Issue by johackim** [tejado/obsidian-gpgCrypt#18]
Hello,

I can't read a GPG file that was encrypted outside of Obsidian.

```bash
gpg -e MyFile.md
```

When I try to open the file `MyFile.md.gpg` on Obsidian, I have the following result:

![2024-06-15_04-27](https://github.com/tejado/obsidian-gpgCrypt/assets/5039608/f66a2379-118e-4d53-9288-a1e01f8951d3)

And when I click on "Decrypt permanently", I have the following error:

```txt
Error: Note not encrypted!
``` 

Thanks for your help!

**Comment by tejado** [comment]
Hi,

gpgCrypt can currently only read armored gpg files and it looks like your file is not armored. This means your file contains just binary data and is not encoded in base64.
If you encrypt files outside of Obsidian, please use the --armor option.

https://www.gnupg.org/documentation/manuals/gnupg24/gpg.1.html
```
--armor 
 -a 
Create ASCII armored output. The default is to create the binary OpenPGP format. 
```

Also mentioned in the README:
https://github.com/tejado/obsidian-gpgCrypt?tab=readme-ov-file#encrypt--decrypt-outside-of-obsidian

Can you test this please?

**Comment by johackim** [comment]
It works, thanks @tejado 😀!
