### ISSUE TITLE
Utilizing an existing key

### ISSUE THREAD

**Issue by Aetherinox** [tejado/obsidian-gpgCrypt#3]
I haven't had a chance to really play with this yet, but I can't tell you the last time I was excited about a plugin. GPG encryption has been at the top of my wishlist for ages. So I really hope this plugin keeps getting updates and it gains attraction, because this is a huge thing, especially if it works with my Yubikey.

Question is, does it currently support existing GPG keys, if so, you may want to write down a quick block in the readme on using an existing key.

I saw that the script allows you to define the `asc` file you want for public/private, however, in order to use an existing, it looks like I'm going to have to have your plugin generate a keypair to start off with, and then look through the structure and overwrite the files with my existing GPG key and then wipe the keypair that were generated by the plugin.

So a simple "howto" on using an existing gpg keypair would be awesome. I checked the readme and while it is early here, I don't see any specific instructions on that.

I did see that there are settings / a dropdown to pick an existing GPG key, but it sort of gets a little confusing when the initial screen wants you to generate a new key instead of having some option like "Use Existing Key".

**Comment by tejado** [comment]
Hey @Aetherinox 
thank you so much for the feedback. That's great to hear!

So yes, gpgCrypt works with OpenPGP smartcards (like the applet in Yubikey) if you use the gpg CLI wrapper mode. I use this on my personal setup.

You are right - there are currently no instructions for using an exisitng key. Thats very good feedback and I will make it more clear in the plugin itself and add a description to the readme.

Of course, gpgCrypt will not override any of your existing keys - that would be fatal. 
As you mentioned, you can adjust the path of the public and private key in the gpgCrypt settings - currently only a path inside your Vault is supported, but you can use encrypted private keys. But it seems not very clear, so I will improve on that, thank you!

**Comment by Aetherinox** [comment]
Awesome to hear.

One other thing for clarification. What triggers the event of encrypting the vault?

I've been re-doing my vault today after I added this plugin. I have a lot of old plugins, and ones I don't use anymore and I'm cleaning / rewriting everything.

I've noticed that if I close and re-open my vault, I see no mention of decrypting the vault, so does this work on a file-by-file basis? I noticed if I right click on a specific file, I see `Encrypt with key pair`.

However, if I use the `Encrypt with key pair`, I see this message:
![9cHI6Sv](https://github.com/tejado/obsidian-gpgCrypt/assets/118329232/e66deb78-c718-4849-8ae4-ebf7cb6026a2)

I've been in the gpgCrypt settings and selected an existing key that I use for my other stuff. So I'm not sure what is failing. As a note, I am also using the GPG CLI wrapper.

![eSlY6wb](https://github.com/tejado/obsidian-gpgCrypt/assets/118329232/1717e5a8-9bd6-4549-b55d-f134fd6e8d06)

**Comment by tejado** [comment]
Yes, it's done file-by-file. gpgCrypt hooks into the read/write functions of Obsidian to transparently encrypts the data immediatly when a Note is saved.
As per issue https://github.com/tejado/obsidian-gpgCrypt/issues/1, I will also add a function to encrypt all notes per default. But be aware: this is only for notes. Non-note files like pictures or PDFs are unfortunately handled differently by Obsidian so they are not encrypted.

The error "Unsuable public key" could have different causes. It might be that you imported it but without any trust. So if you enable "Always trust keys" in gpgCrypt, it might work.

**Comment by Aetherinox** [comment]
Yeah I just went into GPG CLI and looked at my trust and then tried out the "Always trust" setting and that appeared to work. GPG keys appear to have trust in gpg, so I'm not sure what the issue was.

As for the future update to encrypt all files, that would be amazing. I mean it's cool as heck right now I have any GPG encryption in Obsidian, so this is just cool as hell, but adding on to it would be icing on the cake.

And yeah, I read the docs about it doing markdown only, and that's fine by me. The markdown files are 90% of my vault, so it's not a big deal.

This is the coolest damn thing since landing on the moon. I'm a GPG freak and use it for everything, and I've always had an issue with Obsidian not supporting Yubikeys.

**Comment by tejado** [comment]
If you use gpg CLI mode, you don't need public.asc and private.asc. You see this in the settings as these input fields are not anymore there. But the data.json file of the plugin will still have the values.

What do you think of this as a new first-launch dialog instead of just opening the key-gen dialog?
![image](https://github.com/tejado/obsidian-gpgCrypt/assets/3774136/e8301858-dd12-4334-907c-b677f028e7a3)

**Comment by Aetherinox** [comment]
That is 1000% better. Pretty perfect in fact. Gives all the clear information

**Comment by tejado** [comment]
Thanks for the feedback. Will incorporate it.

Yes, I think the same. In my perspective, its already too much text on this new dialog as well but I dont want to remove any info.

**Comment by Aetherinox** [comment]
Here's a demo version, of something if you want to use notes from it. Tried making it short, but you can see how it looks on the dialog itself.

---

## gpgCrypt
Encrypt your Obsidian Notes effortlessly with gpgCrypt.

### Key Pairs

To encrypt / decrypt your notes, gpgCrypt requires a key pair.
- `Public Key` for Encryption
- `Private Key` for Decryption

You may either `Generate` or use an `Existing` key pair to encrypt your notes.
To generate, click **Generate new keypair** below.

If you wish to use your existing key pair, open gpgCrypt Settings below and select an encryption backend:
- OpenPGP.js
- GnuPG CLI

### OpenPGP.js

1. Place your key pair in your Obsidian Vault folder. Keys must be in ASCII format and armored (.asc)
2. Open gpgCrypt Settings and set the **Paths** to your provided .asc keyfiles.

### GnuPG CLI
1. Open gpgCrypt Settings and select the GPG key you wish to use to encrypt your notes.
2. Make sure the **GPG Executable** path is set correctly.

### How to Encrypt Notes
Encryption must be performed individually to each note. To do so, right-click on a note and choose 'Encrypt with key pair'. Right click again to permanently decrypt.

Learn more at https://github.com/tejado/obsidian-gpgCrypt

**Comment by tejado** [comment]
@Aetherinox thanks, great ideas, I will think about it.

**Comment by Aetherinox** [comment]
Sure thing. Anything to help. I've seen a lot of plugins come and go in the Obsidian community, this is one I want to see excel.

**Comment by tejado** [comment]
Implemented in release https://github.com/tejado/obsidian-gpgCrypt/releases/tag/0.2.0

**Comment by Aetherinox** [comment]
Thanks @tejado 
You happen to know the caching time before Obsidian's UI picks up on the update? Still can't seem to pull it.

**Comment by tejado** [comment]
@Aetherinox 
Forgot to update manifest.json in the repo. Should now be possible to update.

**Comment by Aetherinox** [comment]
Awesome thanks, got the update.
